apiVersion: v1
kind: Service
metadata:
  name: location
  labels:
    app: location
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: location
  type: LoadBalancer